---
- name: create OpenHAB-Homekit-Bridge home
  file: path='{{ homekit_home }}' state=directory owner=vagrant group=vagrant
  sudo: yes
- name: checkout OpenHAB-Homekit-Bridge
  git: repo={{ url }} dest={{ homekit_home }}
- name: install OpenHAB-Homekit-Bridge
  command: npm install chdir={{ homekit_home }} creates={{ homekit_home }}/node_modules
