---
- hosts: all
  vars:
    java_home: /opt/java
    openhab_home: /opt/openhab
    files_base: /vagrant/files
    extern_base: "{{ files_base }}/extern"
    jdk_tar: "{{ extern_base }}/jdk-8u25-linux-i586.gz"
    openhab_version: 1.6.1
    openhab_runtime_zip: "{{ extern_base }}/distribution-{{ openhab_version }}-runtime.zip"
    openhab_addons_zip: "{{ extern_base }}/distribution-{{ openhab_version }}-addons.zip"
    openhab_init_script: "{{ files_base }}/openhab/openhab.init"
    openhab_addons:
      - org.openhab.binding.knx-{{ openhab_version }}.jar
      - org.openhab.action.mail-{{ openhab_version }}.jar
      - org.openhab.binding.onewire-{{ openhab_version }}.jar
      - org.openhab.action.xmpp-{{ openhab_version }}.jar
      - org.openhab.binding.http-{{ openhab_version }}.jar
      - org.openhab.persistence.rrd4j-{{ openhab_version }}.jar
    openhab_myopenhab: "{{ extern_base }}/"
    openhab_items:
      - bluetooth.items
      - eib.items
      - http.items
      - onewire.items
      - sunext.items
    openhab_rules:
      - HaustuerAussen.rules
      - gf_lights.rules
      - music.rules
      - sunext.rules
      - Zirkulation.rules
      - kellerlicht.rules
      - rollershutter.rules
      - wlan.rules
    dependencies:
      - apt
      - unzip

  tasks:
    - name: apt install dependencies
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
      sudo: yes
      with_items: dependencies

    - name: create java home
      file: path={{ java_home }} state=directory owner=vagrant group=vagrant
      sudo: yes
    - name: install jdk
      command: tar -xvo -f {{ jdk_tar }} -C {{ java_home }} --strip-components=1 creates={{ java_home }}/bin

    - name: create openhab home
      file: path={{ openhab_home }} state=directory owner=vagrant group=vagrant
      sudo: yes
    - name: install openhab runtime
      command: unzip {{ openhab_runtime_zip }} -d {{ openhab_home }} creates={{ openhab_home }}/webapps
    - name: install openhab addons
      command: unzip {{ openhab_addons_zip }} {{ item }} -d {{ openhab_home }}/addons creates={{ openhab_home }}/addons/{{ item }}
      with_items: openhab_addons
    - name: install openhab init script
      command: cp {{ openhab_init_script }} /etc/init.d/openhab creates=/etc/init.d/openhab
      sudo: yes

    - name: install openhab.cfg
      template: src=../files/openhab/configurations/openhab.cfg.j2 dest={{ openhab_home }}/configurations/openhab.cfg owner=vagrant group=vagrant
    - name: install openhab items
      command: cp {{ files_base }}/openhab/configurations/items/{{ item }} {{ openhab_home }}/configurations/items/{{ item }} creates={{ openhab_home }}/configurations/items/{{ item }}
      with_items: openhab_items
    - name: install openhab rules
      command: cp {{ files_base }}/openhab/configurations/rules/{{ item }} {{ openhab_home }}/configurations/rules/{{ item }} creates={{ openhab_home }}/configurations/rules/{{ item }}
      with_items: openhab_rules
    - name: install openhab sitemaps
      command: cp {{ files_base }}/openhab/configurations/sitemaps/home.sitemap {{ openhab_home }}/configurations/sitemaps/ creates={{ openhab_home }}/configurations/sitemaps/home.sitemap
    - name: install openhab persistence
      command: cp {{ files_base }}/openhab/configurations/persistence/rrd4j.persist {{ openhab_home }}/configurations/persistence/ creates={{ openhab_home }}/configurations/persistence/rrd4j.persist

    - name: start openhab
      service: name=openhab enabled=yes state=started
      sudo: yes
