---
- hosts: all
  vars:
    files_base: /vagrant/files
    extern_base: "{{ files_base }}/extern"
  roles:
 #   - knxd:
 #     role: knxd
    - openhab:
      role: openhab
    - homekit:
      role: homekit
